In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('TexasTurbine (2).csv')

In [4]:
data

,Time stamp,System power generated | (kW),Wind speed | (m/s),Wind direction | (deg),Pressure | (atm),Air temperature | ('C)
0,"Jan 1, 12:00 am",1766.64,9.926,128,1.000480,18.263
1,"Jan 1, 01:00 am",1433.83,9.273,135,0.999790,18.363
2,"Jan 1, 02:00 am",1167.23,8.660,142,0.999592,18.663
3,"Jan 1, 03:00 am",1524.59,9.461,148,0.998309,18.763
4,"Jan 1, 04:00 am",1384.28,9.184,150,0.998507,18.963
...,...,...,...,...,...,...
8755,"Dec 31, 07:00 pm",1234.70,8.848,129,0.998604,19.663
8756,"Dec 31, 08:00 pm",1105.37,8.502,118,1.000090,19.063
8757,"Dec 31, 09:00 pm",1405.71,9.224,117,0.998408,18.463
8758,"Dec 31, 10:00 pm",1221.36,8.799,116,0.998013,18.063
8759,"Dec 31, 11:00 pm",1676.77,9.748,121,1.000380,18.163

In [5]:
del data['Time stamp']

In [6]:
data

,System power generated | (kW),Wind speed | (m/s),Wind direction | (deg),Pressure | (atm),Air temperature | ('C)
0,1766.64,9.926,128,1.000480,18.263
1,1433.83,9.273,135,0.999790,18.363
2,1167.23,8.660,142,0.999592,18.663
3,1524.59,9.461,148,0.998309,18.763
4,1384.28,9.184,150,0.998507,18.963
...,...,...,...,...,...
8755,1234.70,8.848,129,0.998604,19.663
8756,1105.37,8.502,118,1.000090,19.063
8757,1405.71,9.224,117,0.998408,18.463
8758,1221.36,8.799,116,0.998013,18.063
8759,1676.77,9.748,121,1.000380,18.163

In [7]:
df=data.dropna()

In [8]:
df

,System power generated | (kW),Wind speed | (m/s),Wind direction | (deg),Pressure | (atm),Air temperature | ('C)
0,1766.64,9.926,128,1.000480,18.263
1,1433.83,9.273,135,0.999790,18.363
2,1167.23,8.660,142,0.999592,18.663
3,1524.59,9.461,148,0.998309,18.763
4,1384.28,9.184,150,0.998507,18.963
...,...,...,...,...,...
8755,1234.70,8.848,129,0.998604,19.663
8756,1105.37,8.502,118,1.000090,19.063
8757,1405.71,9.224,117,0.998408,18.463
8758,1221.36,8.799,116,0.998013,18.063
8759,1676.77,9.748,121,1.000380,18.163

In [9]:
df=df.rename({'System power generated | (kW)':'System_power_generated','Wind speed | (m/s)':'Wind_speed',
              'Wind direction | (deg)':'Wind_direction','Pressure | (atm)':'Pressure',
              "Air temperature | ('C)":'Air_temperature'},axis=1)

In [10]:
df.columns

Index(['System_power_generated', 'Wind_speed', 'Wind_direction', 'Pressure',
       'Air_temperature'],
      dtype='object')

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, explained_variance_score,median_absolute_error

In [12]:
from sklearn.model_selection import train_test_split
X = df.drop(['System_power_generated'], axis=1).values
y = df['System_power_generated'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [13]:
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

In [21]:
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
# Define CNN model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

# Compile model
model.compile(optimizer='adam', loss='mse')

# Train model
history = model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test))

# Evaluate model
loss = model.evaluate(X_test, y_test, verbose=0)
print("Test Loss: {:.3f}".format(loss))

Epoch 1/50
110/110 [==============================] - 1s 5ms/step - loss: 1250087.0000 - val_loss: 928620.0000
Epoch 2/50
110/110 [==============================] - 0s 3ms/step - loss: 958837.5625 - val_loss: 850381.0625
Epoch 3/50
110/110 [==============================] - 0s 3ms/step - loss: 871148.5000 - val_loss: 777302.6250
Epoch 4/50
110/110 [==============================] - 0s 3ms/step - loss: 803332.9375 - val_loss: 738600.0625
Epoch 5/50
110/110 [==============================] - 0s 3ms/step - loss: 769466.3125 - val_loss: 733071.0625
Epoch 6/50
110/110 [==============================] - 0s 3ms/step - loss: 756149.0625 - val_loss: 718100.2500
Epoch 7/50
110/110 [==============================] - 0s 3ms/step - loss: 737427.3750 - val_loss: 693582.4375
Epoch 8/50
110/110 [==============================] - 0s 3ms/step - loss: 715189.6250 - val_loss: 665847.0625
Epoch 9/50
110/110 [==============================] - 0s 3ms/step - loss: 683514.9375 - val_loss: 633376.6875
Epoch 10/50
110/110 [==============================] - 0s 3ms/step - loss: 641269.3125 - val_loss: 586199.0625
Epoch 11/50
110/110 [==============================] - 0s 3ms/step - loss: 587309.4375 - val_loss: 531840.1875
Epoch 12/50
110/110 [==============================] - 0s 3ms/step - loss: 521418.0312 - val_loss: 459825.4688
Epoch 13/50
110/110 [==============================] - 0s 3ms/step - loss: 445039.5000 - val_loss: 386069.5938
Epoch 14/50
110/110 [==============================] - 0s 3ms/step - loss: 370424.0000 - val_loss: 316863.9375
Epoch 15/50
110/110 [==============================] - 0s 3ms/step - loss: 305256.9375 - val_loss: 262469.3750
Epoch 16/50
110/110 [==============================] - 0s 3ms/step - loss: 254097.7344 - val_loss: 223065.7344
Epoch 17/50
110/110 [==============================] - 0s 3ms/step - loss: 214698.5000 - val_loss: 190685.4062
Epoch 18/50
110/110 [==============================] - 0s 3ms/step - loss: 191018.2656 - val_loss: 175632.6406
Epoch 19/50
110/110 [==============================] - 0s 3ms/step - loss: 175240.7500 - val_loss: 164950.5781
Epoch 20/50
110/110 [==============================] - 0s 3ms/step - loss: 166579.8125 - val_loss: 154047.9219
Epoch 21/50
110/110 [==============================] - 0s 3ms/step - loss: 156900.1719 - val_loss: 146592.2812
Epoch 22/50
110/110 [==============================] - 0s 3ms/step - loss: 149388.8125 - val_loss: 139472.5156
Epoch 23/50
110/110 [==============================] - 0s 3ms/step - loss: 142966.2500 - val_loss: 135200.6406
Epoch 24/50
110/110 [==============================] - 0s 3ms/step - loss: 136964.8750 - val_loss: 127426.5938
Epoch 25/50
110/110 [==============================] - 0s 3ms/step - loss: 134188.8750 - val_loss: 125313.5859
Epoch 26/50
110/110 [==============================] - 0s 3ms/step - loss: 128368.3984 - val_loss: 127623.2109
Epoch 27/50
110/110 [==============================] - 0s 3ms/step - loss: 127098.6172 - val_loss: 121603.0781
Epoch 28/50
110/110 [==============================] - 0s 3ms/step - loss: 124174.1953 - val_loss: 129925.2891
Epoch 29/50
110/110 [==============================] - 0s 3ms/step - loss: 121126.5312 - val_loss: 113880.0859
Epoch 30/50
110/110 [==============================] - 0s 3ms/step - loss: 117774.1562 - val_loss: 110753.4609
Epoch 31/50
110/110 [==============================] - 0s 3ms/step - loss: 115953.7812 - val_loss: 108264.3203
Epoch 32/50
110/110 [==============================] - 0s 3ms/step - loss: 111550.7031 - val_loss: 105893.5859
Epoch 33/50
110/110 [==============================] - 0s 3ms/step - loss: 108809.4375 - val_loss: 103374.5547
Epoch 34/50
110/110 [==============================] - 0s 3ms/step - loss: 107712.7656 - val_loss: 100729.1797
Epoch 35/50
110/110 [==============================] - 0s 3ms/step - loss: 105157.2969 - val_loss: 98086.3438
Epoch 36/50
110/110 [==============================] - 0s 3ms/step - loss: 103834.7344 - val_loss: 101324.1484
Epoch 37/50
110/110 [==============================] - 0s 3ms/step - loss: 103208.7109 - val_loss: 94670.4453
Epoch 38/50
110/110 [==============================] - 0s 3ms/step - loss: 99002.9531 - val_loss: 93130.8125
Epoch 39/50
110/110 [==============================] - 0s 3ms/step - loss: 98236.6016 - val_loss: 95264.8438
Epoch 40/50
110/110 [==============================] - 0s 3ms/step - loss: 95513.6719 - val_loss: 88848.4297
Epoch 41/50
110/110 [==============================] - 0s 3ms/step - loss: 93789.3516 - val_loss: 87308.0469
Epoch 42/50
110/110 [==============================] - 0s 3ms/step - loss: 95791.0078 - val_loss: 97077.6250
Epoch 43/50
110/110 [==============================] - 0s 3ms/step - loss: 91321.6328 - val_loss: 85139.5547
Epoch 44/50
110/110 [==============================] - 0s 3ms/step - loss: 88092.2734 - val_loss: 83438.5469
Epoch 45/50
110/110 [==============================] - 0s 3ms/step - loss: 87563.0938 - val_loss: 91157.8828
Epoch 46/50
110/110 [==============================] - 0s 3ms/step - loss: 86182.5234 - val_loss: 79501.2578
Epoch 47/50
110/110 [==============================] - 0s 3ms/step - loss: 83739.8984 - val_loss: 79639.7188
Epoch 48/50
110/110 [==============================] - 0s 3ms/step - loss: 83601.0469 - val_loss: 83722.7500
Epoch 49/50
110/110 [==============================] - 0s 3ms/step - loss: 80737.4375 - val_loss: 75513.1562
Epoch 50/50
110/110 [==============================] - 0s 3ms/step - loss: 79437.5469 - val_loss: 73838.9141
Test Loss: 73838.914